version: '3.7'
services:
  airflow:
    image: apache/airflow:2.6.0
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:senha123@postgres:5432/northwind
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: northwind
    ports:
      - "5432:5432"  # Expor a porta no host local
