version: '3.7'
services:
  airflow:
    image: apache/airflow:2.6.0
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://{user}:{password}@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin                # Nome do usuário
      POSTGRES_PASSWORD: senha123         # Senha
      POSTGRES_DB: northwind              # Nome do banco
    ports:
      - "5432:5432"
